import time

from app.vector_store import VECTOR_DB_PATH
from app.retrieval import retrieve
from app.llm import get_embeddings, get_llm
from langchain_chroma import Chroma
from langchain_core.prompts import PromptTemplate
from app.generation import generate_answer_with_usage
from app.verification import verify_answer_with_usage, decide_result
from app.tracing import Trace
from app.query_transform import transform_query
from app.reranker import rerank
from app.hybrid_retrieval import create_bm25_retriever, hybrid_retrieve
from langsmith import traceable

def _apply_usage_metadata(span, usage):
    if not usage:
        return

    usage_dict = usage if isinstance(usage, dict) else {}
    span.metadata["input_tokens"] = usage_dict.get("input_tokens", usage_dict.get("prompt_tokens", 0))
    span.metadata["output_tokens"] = usage_dict.get("output_tokens", usage_dict.get("completion_tokens", 0))
    span.metadata["total_tokens"] = usage_dict.get("total_tokens", usage_dict.get("input_tokens", 0) + usage_dict.get("output_tokens", 0))


def build_context_from_results(results) -> str:
    context_parts = []
    for doc, _score in results:
        chunk_id = doc.metadata.get("chunk_id", "unknown")
        source = doc.metadata.get("source", "unknown")

        context_parts.append(
            f"Chunk ID: {chunk_id}\n"
            f"Source: {source}\n"
            f"Content: {doc.page_content}\n"
        )

    return "\n".join(context_parts)


def answer_question(question: str, k: int = 5) -> str:
    vector_store = Chroma(
        persist_directory=VECTOR_DB_PATH,
        embedding_function=get_embeddings(),
    )
    results = retrieve(vector_store, question, k=k)
    context = build_context_from_results(results)
    return generate_answer(question, context)

@traceable(name="regeneration", run_type="chain")
def regenerate_answer(
    question,
    context,
    previous_answer,
    verification_result
):

    feedback = "\n\n".join(
        [
            f"Claim: {claim.claim}\n"
            f"Verdict: {claim.verdict}\n"
            f"Reason: {claim.reason}"
            for claim in verification_result.claims
        ]
    )

    prompt_template = PromptTemplate(
        input_variables=[
            "question",
            "context",
            "previous_answer",
            "feedback"
        ],
        template="""
You are correcting an answer generated by a RAG system.

Use ONLY the provided context.

Question:
{question}

Context:
{context}

Previous Answer:
{previous_answer}

Verification Feedback:
{feedback}

Generate a corrected answer.

Rules:
1. Keep claims that are supported by the context.
2. Correct partially supported claims.
3. Remove unsupported claims.
4. Do not add information from your own knowledge.
5. If the context does not contain enough information,
   explicitly say that there is not enough information.
6. Cite each important factual claim with the relevant chunk ID in this format: [chunk: CHUNK_ID]
7. Only use chunk IDs that appear in the context.

Corrected Answer:
"""
    )

    prompt = prompt_template.format(
        question=question,
        context=context,
        previous_answer=previous_answer,
        feedback=feedback
    )

    response = get_llm().invoke(prompt)

    return response.content



@traceable(name="rag_pipeline", run_type="chain")
def run_question(question: str, k: int = 5, max_attempts: int = 2) -> dict:
    trace = Trace()

    retrieval_span = trace.start_span(
        "retrieval",
        metadata={
            "k": k,
        },
    )
    vector_store = Chroma(
        persist_directory=VECTOR_DB_PATH,
        embedding_function=get_embeddings(),
    )
    bm25 = create_bm25_retriever()
    transformed_query = transform_query(question)
    print("\n========== QUERY TRANSFORMATION ==========")
    print(f"Original:    {question}")
    print(f"Transformed: {transformed_query}")

    retrieval_start = time.perf_counter()
    retrieval_timings = {}
    results = hybrid_retrieve(
        vector_store,
        bm25,
        transformed_query,
        k=k,
        timings=retrieval_timings,
    )
    reranking_start = time.perf_counter()
    reranked_results = rerank(
        question,
        results,
        top_n=3,
    )
    retrieval_timings["reranking"] = time.perf_counter() - reranking_start
    retrieval_timings["total"] = time.perf_counter() - retrieval_start
    print("\n========== RETRIEVAL TIMING ==========")
    print(f"Dense:       {retrieval_timings['dense'] * 1000:.1f} ms")
    print(f"BM25:        {retrieval_timings['bm25'] * 1000:.1f} ms")
    print(f"RRF:         {retrieval_timings['rrf'] * 1000:.1f} ms")
    print(f"Reranking:   {retrieval_timings['reranking'] * 1000:.1f} ms")
    print(f"Total:       {retrieval_timings['total'] * 1000:.1f} ms")
    retrieval_span.metadata["chunks_retrieved"] = len(results)
    retrieval_span.end()

    context = build_context_from_results(
        [
            (doc, score)
            for doc, score in reranked_results
        ]
    )
    result = run_rag_pipeline(question=question, context=context, max_attempts=max_attempts, trace=trace)
    result["trace"] = trace
    return result


def run_rag_pipeline(
    question,
    context,
    max_attempts=2,
    trace=None
):
    if trace is None:
        trace = Trace()

    answer = None
    verification_result = None

    for attempt in range(max_attempts):
        generation_span = trace.start_span(
            "generation",
            metadata={
                "model": "gpt-4o",
                "attempt": attempt + 1,
            },
        )
        generation_result, generation_usage = generate_answer_with_usage(question, context)
        answer = generation_result.answer
        answer_status = generation_result.answer_status
        generation_span.metadata["answer_status"] = answer_status
        _apply_usage_metadata(generation_span, generation_usage)
        generation_span.end()

        print(f"\n===== ATTEMPT {attempt + 1} =====")
        print("\nANSWER:")
        print(answer)

        if answer_status == "ABSTAINED":
            decision = "ACCEPT"
            print(f"\nDECISION: {decision}")
            return {
                "answer": answer,
                "answer_status": answer_status,
                "decision": decision,
                "verification": None,
                "trace": trace,
            }

        verification_span = trace.start_span(
            "verification",
            metadata={
                "model": "gpt-4o",
                "attempt": attempt + 1,
            },
        )
        verification_result, verification_usage = verify_answer_with_usage(question, answer, context)
        _apply_usage_metadata(verification_span, verification_usage)
        verification_span.metadata["claims"] = len(verification_result.claims)
        verification_span.metadata["supported"] = sum(
            1 for claim in verification_result.claims if claim.verdict == "SUPPORTED"
        )
        verification_span.metadata["unsupported"] = sum(
            1 for claim in verification_result.claims if claim.verdict == "UNSUPPORTED"
        )
        verification_span.metadata["partially_supported"] = sum(
            1 for claim in verification_result.claims if claim.verdict == "PARTIALLY_SUPPORTED"
        )
        verification_span.end()

        print("\nVERIFICATION:")
        for claim in verification_result.claims:
            print(f"\nClaim: {claim.claim}")
            print(f"Verdict: {claim.verdict}")
            print(f"Reason: {claim.reason}")
            print(f"Evidence chunk: {claim.evidence_chunk_id}")

        decision = decide_result(verification_result)
        print(f"\nDECISION: {decision}")

        if decision == "ACCEPT":
            return {
                "answer": answer,
                "answer_status": answer_status,
                "decision": decision,
                "verification": verification_result,
                "trace": trace,
            }

        if attempt == max_attempts - 1:
            return {
                "answer": answer,
                "answer_status": answer_status,
                "decision": decision,
                "verification": verification_result,
                "trace": trace,
            }

        print("\nRegenerating answer...")
        regeneration_span = trace.start_span(
            "regeneration",
            metadata={
                "attempt": attempt + 1,
                "previous_decision": decision,
            },
        )
        answer = regenerate_answer(
            question,
            context,
            answer,
            verification_result
        )
        regeneration_span.end()

    return {
        "answer": answer,
        "decision": decide_result(verification_result),
        "verification": verification_result,
        "trace": trace,
    }