from app.vector_store import VECTOR_DB_PATH
from app.retrieval import retrieve
from app.llm import get_embeddings, get_llm
from langchain_chroma import Chroma
from langchain_core.prompts import PromptTemplate
from app.generation import generate_answer
from app.verification import verify_answer, decide_result


def build_context_from_results(results) -> str:
    context_parts = []
    for doc, _score in results:
        chunk_id = doc.metadata.get("chunk_id", "unknown")
        source = doc.metadata.get("source", "unknown")

        context_parts.append(
            f"Chunk ID: {chunk_id}\n"
            f"Source: {source}\n"
            f"Content: {doc.page_content}\n"
        )

    return "\n".join(context_parts)


def answer_question(question: str, k: int = 5) -> str:
    vector_store = Chroma(
        persist_directory=VECTOR_DB_PATH,
        embedding_function=get_embeddings(),
    )
    results = retrieve(vector_store, question, k=k)
    context = build_context_from_results(results)
    return generate_answer(question, context)


def regenerate_answer(
    question,
    context,
    previous_answer,
    verification_result
):

    feedback = "\n\n".join(
        [
            f"Claim: {claim.claim}\n"
            f"Verdict: {claim.verdict}\n"
            f"Reason: {claim.reason}"
            for claim in verification_result.claims
        ]
    )

    prompt_template = PromptTemplate(
        input_variables=[
            "question",
            "context",
            "previous_answer",
            "feedback"
        ],
        template="""
You are correcting an answer generated by a RAG system.

Use ONLY the provided context.

Question:
{question}

Context:
{context}

Previous Answer:
{previous_answer}

Verification Feedback:
{feedback}

Generate a corrected answer.

Rules:
1. Keep claims that are supported by the context.
2. Correct partially supported claims.
3. Remove unsupported claims.
4. Do not add information from your own knowledge.
5. If the context does not contain enough information,
   explicitly say that there is not enough information.

Corrected Answer:
"""
    )

    prompt = prompt_template.format(
        question=question,
        context=context,
        previous_answer=previous_answer,
        feedback=feedback
    )

    response = get_llm().invoke(prompt)

    return response.content




def run_question(question: str, k: int = 5, max_attempts: int = 2) -> dict:
    vector_store = Chroma(
        persist_directory=VECTOR_DB_PATH,
        embedding_function=get_embeddings(),
    )
    results = retrieve(vector_store, question, k=k)
    context = build_context_from_results(results)
    return run_rag_pipeline(question=question, context=context, max_attempts=max_attempts)


def run_rag_pipeline(
    question,
    context,
    max_attempts=2
):
    answer = generate_answer(question, context)

    for attempt in range(max_attempts):
        print(f"\n===== ATTEMPT {attempt + 1} =====")
        print("\nANSWER:")
        print(answer)

        verification_result = verify_answer(question, answer, context)

        print("\nVERIFICATION:")
        for claim in verification_result.claims:
            print(f"\nClaim: {claim.claim}")
            print(f"Verdict: {claim.verdict}")
            print(f"Reason: {claim.reason}")

        decision = decide_result(verification_result)
        print(f"\nDECISION: {decision}")

        if decision == "ACCEPT" or attempt == max_attempts - 1:
            return {
                "answer": answer,
                "decision": decision,
                "verification": verification_result
            }

        print("\nRegenerating answer...")
        answer = regenerate_answer(
            question,
            context,
            answer,
            verification_result
        )